project:
  type: website

website:
  description: "Sam's blog"
  site-url: https://wx4stg.com # you must change this appropriately for RSS feeds to work properly
  title: "Sam's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/wx4stg
      - icon: bluesky
        href: https://bsky.app/profile/wx4stg.com
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



